# Generated by Django 5.1.1 on 2024-10-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_recompensas'),
    ]

    operations = [
        migrations.AddField(
            model_name='misiones',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
