# Generated by Django 5.1.1 on 2024-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_misiones_completada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misiones',
            name='completada',
        ),
        migrations.AlterField(
            model_name='misiones',
            name='tipo',
            field=models.TextField(max_length=50),
        ),
    ]
