# Generated by Django 5.1.1 on 2024-11-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
